import { Providers } from './providers';
import { Header } from '../src/components/ui';
import { Navigation } from '../src/components/layout/Navigation';
import './globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header>
            <Navigation />
          </Header>
          <div className="container">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
