import { Providers } from './providers';
import { Header, Popup } from '../components/ui';
import { Navigation } from './Navigation';
import './globals.css';
import React from 'react';
import { usePopupContext } from '../context/PopupContext';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header>
            <Navigation />
          </Header>
          <div className="container">{children}</div>
          <Popup useContext={usePopupContext} />
        </Providers>
      </body>
    </html>
  );
}
