export const treatments = [
    'Manicure',
    'Nail Extension New Set',
    'Nail Reinforcement New Set',
    'Nail Extension Refill',
    'Nail Reinforcement Refill',
    'Single Eyelashes Extensions New Set',
    'Single Eyelashes Extensions Refill',
    'Volume Eyelashes Extensions New Set (2-3D)',
    'Volume Eyelashes Extensions Refill (2-3D)',
    'Volume Eyelashes Extensions New Set (4-6D)',
    'Volume Eyelashes Extensions Refill (4-6D)',
    'Lash Lift',
    'Eyebrow Shaping and Waxing',
    'Henna Brow with Eyebrow Geometry',
    'Eyelashes Removal',
    'Gel Removal with Regular Manicure',
    'Gel Polish Removal',
];
