export const treatments = [
    'Manikyr',
    'Nagelförlängning Nytt Set',
    'Nagelförstärkning Nytt Set',
    'Nagelförlängning Påfyllning',
    'Nagelförstärkning Påfyllning',
    'Singelfransar Nytt Set',
    'Singelfransar Påfyllning',
    'Volymfransar Nytt Set (2-3D)',
    'Volymfransar Påfyllning (2-3D)',
    'Volymfransar Nytt Set (4-6D)',
    'Volymfransar Påfyllning (4-6D)',
    'Lashlift',
    'Plockning och forming av bryn',
    'Henna brow med ögonbrynsgeometri',
    'Borttagning fransar',
    'Borttagning gel med vanlig manikyr',
    'Borttagning Gellack',
];
